# pu001.yml
# pw: letmein123
---

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    domain_name_servers:
          - 192.0.2.10
          - 192.0.2.11
    range_begin: 172.16.192.1
    range_end: 172.16.255.253


dhcp_global_domain_name: avalon.lan
dhcp_global_booting: allow
dhcp_global_bootp: allow
dhcp_global_filename: boot.img
dhcp_global_domain_name_servers:
      - 8.8.8.8
      - 8.8.4.4
dhcp_global_routers: 192.0.2.254
dhcp_global_max_lease_time: 43200
