dhcp_subnets:

  - ip: 172.16.0.0
    netmask: 255.255.128.0
    domain_name_servers:
          - 192.0.2.10
          - 192.0.2.11
    range_begin: 172.16.0.2
    range_end: 172.16.127.254
    max_lease_time: 43300
    routers: 172.16.255.254

  - ip: 172.16.128.0
    netmask: 255.255.192.0
    domain_name_servers:
          - 192.0.2.10
          - 192.0.2.11
    range_begin: 172.16.128.1
    range_end: 172.16.191.254
    max_lease_time: 43300
    pools:
        - range_begin: 172.16.192.1
        - range_end: 172.16.255.253
        - allow: 'members of "vbox"'
        - max_lease_time: 14400


dhcp_global_domain_name: avalon.lan
dhcp_global_domain_name_servers:
      - 8.8.8.8
      - 8.8.4.4
dhcp_global_routers: 192.0.2.254
