rhbase_install_packages:
  - dhcp

rhbase_firewall_allow_services:
  - dhcp

dhcp_global_domain_name: avalon.lan

dhcp_global_domain_name_servers:
  - 192.0.2.10
  - 192.0.2.11

dhcp_global_routers: 172.16.255.254

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    domain_name_servers:
      - 172.16.255.254
    max_lease_time: 43200
    pools:
      - default_lease_time: 14400
        range_begin: 172.16.192.1
        range_end: 172.16.255.253
        allow: unknown-clients

dhcp_hosts:
  - name: cl1
    mac: '08:00:27:AC:CE:4A'
    ip: 172.16.128.2
