# pu001.yml
# pw: letmein123
---
rhbase_firewall_allow_services:
  - dns

bind_zone_name: avalon.lan

bind_zone_master_server_ip: 192.0.2.10

bind_zone_networks:
  - "192.0.2"
  - "172.16"

bind_allow_query: 
  - any
  
  
bind_listen_ipv4:
  - any
  

bind_zone_name_servers:
  - pu001
  - pu002