# site.yml
# pw: letmein123
---
- hosts: pu004
  sudo: true
  roles: 
    - bertvv.rh-base
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
- hosts: pu001
  sudo: true
  roles: 
    - bertvv.bind
