# site.yml
# pw: letmein123
---
- hosts: pu004
  become: true
  pre_tasks:
    - name: copy certificate
      copy: src=Files/ca.crt dest=/etc/pki/tls/certs/ca.crt
    - name: copy certificate key
      copy: src=Files/ca.key dest=/etc/pki/tls/private/ca.key
      
  roles: 
    - bertvv.rh-base
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
- hosts: pu001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind

- hosts: pu002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind
    
- hosts: pr011
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd
    
- hosts: pr001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.dhcp